### ISSUE TITLE
Can't refine Edison, New Jersey search by localadmin placetype

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-www-spelunker#11]
Searching for `Edison` results in [many many results](https://whosonfirst.mapzen.com/spelunker/search/?q=edison). 

I know the Edison I want is a `localadmin`, so I use the right sidebar to filter down:

```
filter by placetype
venue 1,863 neighbourhood 26 locality 9 localadmin 4 county 1
```

But [clicking](https://whosonfirst.mapzen.com/spelunker/search/?q=edison&placetype=localadmin) `localadmin` results in sad cat:

```
😿 can not find anything matching edison
```

But pulling up the individual record by WOF ID does work!

* https://whosonfirst.mapzen.com/spelunker/id/404478273/

**Comment by thisisaaronland** [comment]
This may simply be an indexing thing. As in: the record has not been indexed, because that still happens independent of any atomic update (to a record).

I am re-indexing the Spelunker now and we'll see...
