### ISSUE TITLE
circa dates not represented in record title

### ISSUE THREAD

**Issue by burritojustice** [whosonfirst/whosonfirst-www-spelunker#111]
https://whosonfirst.mapzen.com/spelunker/id/572206999/

`Mariachi's Taqueria (? - uuuu) 353/454/983/353454983.geojson`

```
edtf
 cessation 2010-09~
 inception uuuu
```

**Comment by thisisaaronland** [comment]
It's more that `edtf:cessation` dates are not displayed. I may close this ticket shortly and reference it in a broader "display dates"  issue that would aim to account for all the date combinations.
