### ISSUE TITLE
Concordances page links to filters with ampersands don't correctly execute

### ISSUE THREAD

**Issue by simonw** [whosonfirst/whosonfirst-www-spelunker#114]
e.g. this page: https://whosonfirst.mapzen.com/spelunker/concordances/nycgov_dca/

<img width="1314" alt="cursor_and_who_s_on_first_spelunker___who_s_on_first_concordances_with_new_york_city_department_of_consumer_affairs" src="https://user-images.githubusercontent.com/9599/28548011-7eb7f79c-7086-11e7-8ce6-150063c55931.png">

The *Bars & Pubs* filter links to https://whosonfirst.mapzen.com/spelunker/concordances/nycgov_dca/?&category=Bars%20&%20Pubs

Which currently says this:

<img width="935" alt="who_s_on_first_spelunker___who_s_on_first_concordances_with_new_york_city_department_of_consumer_affairs" src="https://user-images.githubusercontent.com/9599/28547964-3b92de82-7086-11e7-8fdb-2e30f70d1381.png">

The link to *Retail* works fine - as do the others without an ampersand: https://whosonfirst.mapzen.com/spelunker/concordances/nycgov_dca/?&category=Retail

**Comment by thisisaaronland** [comment]
Fixed modulo the usual JS cache-busting dance (which is a separate issue). Apologies for the poor Internet typing, which was my bad.
