### ISSUE TITLE
Chile cities classified as in Switzerland

### ISSUE THREAD

**Issue by cbeddow** [whosonfirst/whosonfirst-www-spelunker#131]
Not sure if this is the correct place to report this, but see this search and notice ow Chilean place names are being said in the description to be in Switzerland

https://whosonfirst.mapzen.com/spelunker/search/?q=santiago+chile

**Comment by stepps00** [comment]
@cbeddow - thanks, this is the correct place to file an issue! 

I'll take a look and propose a data fix shortly.

**Comment by stepps00** [comment]
Closing and preferring https://github.com/whosonfirst-data/whosonfirst-data/issues/992
