### ISSUE TITLE
Reindex Spelunker with the most recent whosonfirst-data-latest.db file

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-spelunker#141]
The latest distribution file ([here](https://dist.whosonfirst.org/sqlite/)) includes various updates that are not yet reflected in the Spelunker, like locality work in the UK and France.

Semi-related: [whosonfirst-data/1195](https://github.com/whosonfirst-data/whosonfirst-data/issues/1195), [whosonfirst-www-spelunker/137](https://github.com/whosonfirst/whosonfirst-www-spelunker/issues/137)

**Comment by pathmapper** [comment]
Maybe related:

https://spelunker.whosonfirst.org/search/?q=Ohiya

gives no result, but there's a record:

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/129/315/424/9/1293154249.geojson

**Comment by thisisaaronland** [comment]
The Spelunker was manually re-indexed with all admin data 20190714/15.
