### ISSUE TITLE
Some records in GitHub and distribution files do not appear in the Spelunker

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-spelunker#142]
https://github.com/whosonfirst-data/whosonfirst-data/issues/1169
https://github.com/whosonfirst-data/whosonfirst-data/issues/1195

There are a few records that I've found in the Bahamas and Bahrain that are in the distribution files, but not in the Spelunker.

Examples:
https://spelunker.whosonfirst.org/id/85669043/
- should populate: https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/856/690/43/85669043.geojson

https://spelunker.whosonfirst.org/id/85669053/
- should populate: https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/856/690/53/85669053.geojson

https://spelunker.whosonfirst.org/id/85669039/
- should populate: https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/856/690/39/85669039.geojson

Possibly related (?): https://github.com/whosonfirst/whosonfirst-www-spelunker/issues/137

**Comment by thisisaaronland** [comment]
Fixed as of 20190715/16 re-indexing.
