### ISSUE TITLE
Map tiles are not loading in the Spelunker

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-spelunker#151]
https://spelunker.whosonfirst.org/id/102191575/

When loading this page, I'm unable to get map tiles to load. I see the following: 

<img width="1185" alt="Screen Shot 2021-08-02 at 10 22 10 AM" src="https://user-images.githubusercontent.com/18567700/127900433-253b7107-9c77-40b0-8be0-6970c5f054c6.png">

Looking at the console logs, I see 404 / httprequest errors.

**Comment by nvkelso** [comment]
I jumped to a random place and the map does load: https://spelunker.whosonfirst.org/id/1209775309/

@stepps00 Is it just this place that has a problem loading map tiles for you?

**Comment by stepps00** [comment]
Hmm.. looks like this is fixed. Map tiles appear for me on both links.

I'll close this issue since it's fixed, but here are the console logs from earlier, fwiw:

<img width="987" alt="Screen Shot 2021-08-02 at 10 22 26 AM" src="https://user-images.githubusercontent.com/18567700/127927546-6be633c9-46bf-43a2-8666-e1d10ae34cad.png">

**Comment by nvkelso** [comment]
@idees as this might have to do with the new CDN and someone else was having low zoom problems recently?
