### ISSUE TITLE
Can't find Korblex (depreciated record)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-www-spelunker#34]
When I search for the ID I get it, https://whosonfirst.mapzen.com/spelunker/id/85828813/#9/41.1004/-123.8200

But searching the name won't return anything (it should). And it's not listed in the descendants of the parent locality (it should be).

**Comment by thisisaaronland** [comment]
https://whosonfirst.mapzen.com/spelunker/search/?q=Korblex&include=deprecated

See also: https://github.com/whosonfirst/whosonfirst-www-spelunker/issues/27

**Comment by thisisaaronland** [comment]
![screen shot 2016-06-30 at 11 31 22](https://cloud.githubusercontent.com/assets/12658759/16499657/3e12fb9a-3eb6-11e6-891a-2d11333fdebb.png)
