### ISSUE TITLE
Filter by geometry type

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-spelunker#40]
It would be great to have a **`filter by geometry`** option in the Spelunker to show how many point features and how many polygon features are included in search results. This is helpful in quality checking admin data; this filter would allow us to jump between point records and polygon records in our search of Chicago neighbourhoods (shown below):

<img width="1272" alt="screen shot 2016-08-10 at 2 40 00 pm" src="https://cloud.githubusercontent.com/assets/18567700/17572282/7a53048e-5f08-11e6-938e-82e85d10aa77.png">

**Comment by thisisaaronland** [comment]
Done - https://whosonfirst.mapzen.com/spelunker/recent/?&geometry=point

**Comment by nvkelso** [comment]
Super helpful to debug locality and placetypes that still need work, thank you!

**Comment by stepps00** [comment]
This is great!
