### ISSUE TITLE
Integrate the Descender tool into the Spelunker

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-spelunker#51]
The Descender tool (repository [here](https://github.com/burritojustice/wof-descender), working version [here](https://burritojustice.github.io/wof-descender/)) should be integrated into the Spelunker, with links to the Descender added to the `index.html`, `id.html`, and `descendant.html` files.

Opening this issue to track progress on integrating the Descender into the Spelunker.

**Comment by nvkelso** [comment]
Dude, this is awesome!

**Comment by thisisaaronland** [comment]
Closing this ticket because it all works on dev and remaining tickets are being tracked separately.
