### ISSUE TITLE
Use the mapzen.whosonfirst.config.js file to define API specifics

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-spelunker#62]
Things like:

* The API endpoint (dev vs. prod)
* The API key

Related: The `templates/default/mapzen.whosonfirst.config.js.erb` file in the `chef-whosonfirst_spelunker` Chefworks repo.

**Comment by dphiffer** [comment]
Note to self: remember to update berks for *both* dev and prod.
