### ISSUE TITLE
Why is the percentage progress wrong with the bundler?

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-spelunker#68]
Example: [postal codes in France](https://whosonfirst.dev.mapzen.com/spelunker/download/85633147/#4/45.02/2.81)

This should be more like 20% not 5%
![screen shot 2017-01-12 at 14 35 25](https://cloud.githubusercontent.com/assets/38114/21911333/5ff72a06-d8ee-11e6-9c53-2ca9f55281ae.png)

cc @thisisaaronland

**Comment by thisisaaronland** [comment]
Removing from the Bundler milestone for now because issue #73 

Simply disable if figuring this out will delay launch.
