### ISSUE TITLE
Download link from query results is busted

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-spelunker#74]
The link that says "Download descendants" from a page like [this one](https://whosonfirst.dev.mapzen.com/spelunker/id/85632695/descendants/?exclude=nullisland#3/37.05/116.28) doesn't take the path prefix into account (i.e., `/download/[id]` instead of `/spelunker/download/[id]`).

Assigning this to @stepps00 (who discovered it) as an exercise. Take a look at how the path is constructed [here](https://github.com/whosonfirst/whosonfirst-www-spelunker/blob/dev-bundler/www/templates/id.html#L112) to see how this should be fixed.

**Comment by stepps00** [comment]
[This commit](https://github.com/whosonfirst/whosonfirst-www-spelunker/commit/2d5d4511e0a49055e02260e87c928c6ca504dd01) fixes the issue by adding `{{ url_for('index') }}` to the url structure.

**Comment by stepps00** [comment]
[This commit](https://github.com/whosonfirst/whosonfirst-www-spelunker/commit/a5279650e86791de7b2d99df6b335f10f5be2e0c) removed duplicate `/` in the download descendants url.

This link should now be fixed in the `dev` branch.

**Comment by dphiffer** [comment]
Hooray! \o/
