### ISSUE TITLE
Modified date clutters up main search results view

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-www-spelunker#77]
I search for San Francisco and the new view looks like below. There's a lot of extra cruft around recently modified, often wrapping to 2nd line and generally too much. 

I'd like the modified date stuff to either only appear if I'm using the modified endpoint, or an an optional show in the default view (disabled by default).

- https://whosonfirst.mapzen.com/spelunker/search/?q=san+francisco#3/-9.36/-48.57

<img width="624" alt="screen shot 2017-01-13 at 15 23 48" src="https://cloud.githubusercontent.com/assets/853051/21949119/8b27d534-d9a4-11e6-83de-b21d002a56f5.png">

**Comment by thisisaaronland** [comment]
Closing since it is less cluttered now.
