### ISSUE TITLE
Use Refill tangram scene file as remote link

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-www-spelunker#8]
We launched with an embedded scene file using a beta version of Refill. That style is now a thing, and the Spelunker should point at the one over at:

* https://github.com/tangrams/refill/blob/gh-pages/refill.yaml
* https://github.com/tangrams/refill/blob/gh-pages/images/poi_icons_18%402x.png

So we pick up future enhancements for free.

**Comment by thisisaaronland** [comment]
Cross-domain hoohah over HTTPS will make this a problem. Also I would prefer to keep everything local and contained.

It's easy enough to add a target to the Makefile though.
