### ISSUE TITLE
command line version of bundler that streams to disk

### ISSUE THREAD

**Issue by burritojustice** [whosonfirst/whosonfirst-www-spelunker#84]
for giant Bundler downloads, where someone wants to download more than a few hundred or couple of thousand placetypes -- say all 10 million venues in the US -- a command-line app might be good. something like `bundler --wofparent 85633793 --placetype "county, region"`

Was thinking Node since we could port some of the existing bundler code? But I'm pretty agnostic.

**Comment by thisisaaronland** [comment]
Closing because https://github.com/whosonfirst/go-whosonfirst-api#wof-api
