### ISSUE TITLE
Investigate memory optimizations for the bundler

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-spelunker#85]
Presently the bundler [accumulates](https://github.com/whosonfirst/whosonfirst-www-spelunker/blob/master/www/static/javascript/mapzen.whosonfirst.bundler.js#L227) all of its WOF records as a giant data structure. I wonder if this might run faster if we stored each feature as a string instead of parsing it?

**Comment by thisisaaronland** [comment]
Closing this for now since, you know, we shipped!
