### ISSUE TITLE
Add download option for simple attributes 

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-www-spelunker#91]
In the command line `wof-csv-to-feature-collection` script we allow either "all" original WOF properties with all their nesting (the default in the Spelunker download now), or a simpler "editor" template that has far fewer properties that are easy to work with in an editor like QGIS.

We should add a property template option to the download option to enable the same functionality. This would be useful for Mapzen's own workflow for editing neighbourhoods, and many other people don't need to parse thru a 100 empty name fields, either.

See:

- https://github.com/whosonfirst/py-mapzen-whosonfirst-utils/blob/master/scripts/wof-csv-to-feature-collection#L103-L104

Specifically instead of 100s of columns the editor template only has:

* `name`
* `id`
* `placetype`
* `parent_id`
* `is_current`
* `is_landuse_aoi`
* `supersedes`
* `superseded_by`
* `deprecated`
* `cessation`
* `eng_preferred_name`
* `eng_variant_name`
* `max_zoom`
* `min_zoom`
* `lbl_latitude`
* `lbl_longitude`
* `is_funky`
* `is_hard_boundary`
* `is_official`
* `tier_locality`
* `country_id`
* `region_id`
* `locality_id`
* `wof_country`
* `iso_country`
* `mz_note`
* `src_geom`

And if it's a neighbourhood placetype it also adds:

* `is_funky`
* `is_hard_boundary`
* `is_landuse_aoi`
* `is_official`
* `max_zoom`
* `min_zoom`
* `tier_locality`

**Comment by thisisaaronland** [comment]
@dphiffer - this should be relatively straightforward to implement (client-side) assuming we can fetch the aliases files directly from here: https://github.com/whosonfirst/whosonfirst-properties/tree/master/aliases because blah blah blah CORS blah blah blah.

**Comment by dphiffer** [comment]
I am looking into this now. I'll add a new JSON alias file to whosonfirst-properties and a Makefile target to update a local copy in the Spelunker. I don't think we should use the existing one, since it maps simple-to-complex (`name` turns into `wof:name`) rather than the reverse (`wof:name` into `name`).

**Comment by dphiffer** [comment]
Okay I have this up and running on https://whosonfirst.dev.mapzen.com/spelunker/

Let me know if it looks okay...

**Comment by dphiffer** [comment]
^ @nvkelso @thisisaaronland

**Comment by nvkelso** [comment]
Nice! It's working great for me, thank you :)

**Comment by nvkelso** [comment]
Some comparisons:

**GeoJSON gets almost 50% smaller** 

<img width="351" alt="screen shot 2017-07-06 at 11 07 48" src="https://user-images.githubusercontent.com/853051/27925948-78dfed88-623b-11e7-95cd-8d9d344c1b9c.png">

**Shapefile DBF shows larger win** as null props take up more DBF space:

<img width="355" alt="screen shot 2017-07-06 at 11 08 31" src="https://user-images.githubusercontent.com/853051/27925949-78e186d4-623b-11e7-9104-40febeac6ecf.png">
